name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch :
jobs:

  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@3.0.3
      - name: Restore dependencies
        run: dotnet restore ./path/to/your.sln
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  Build:
    runs-on: ubuntu-latest
    needs: [Security]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: ./OnlineGames.Server
      run: dotnet restore
      
    - name: Build
      working-directory: ./OnlineGames.Server
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: ./OnlineGames.Server
      run: dotnet test --no-build --verbosity normal
      
    - name : Upload repo
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: .

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sashovas
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./OnlineGames.Server
          file: ./OnlineGames.Server/Dockerfile 
          push: true
          tags: ghcr.io/sashovas/online_games_api:latest

      - name: Verify Image is Pushed
        run: echo "Image successfully pushed to ghcr.io/sashovas/online_games_api:latest"


